In [1]:
import numpy as np

In [2]:
x=[1,2,3]
print(x)


[1, 2, 3]


In [4]:
matr=[[22,3,0],[8,6,5],[25,0,0],[7,6,13],[0,24,1]]
arr = np.array(matr)
print(arr)

[[22  3  0]
 [ 8  6  5]
 [25  0  0]
 [ 7  6 13]
 [ 0 24  1]]


In [6]:
np.sum(arr)

120

In [7]:
arr.sum()

120

In [8]:
arr[0].sum()

25

In [10]:
print(arr.sum(axis=1))

[25 19 25 26 25]


In [13]:
arr.shape

(5, 3)

In [15]:
print(arr.sum(axis=1, keepdims=True).shape)
print(arr.sum(axis=1).shape)

(5, 1)
(5,)


In [25]:
ones = np.ones((3,), dtype=int)
print(ones)

[1 1 1]


In [26]:
np.dot(arr,ones)

array([25, 19, 25, 26, 25])

In [37]:
print(np.sum(arr,axis=0))
print(np.dot(np.ones((1,5), dtype=int),arr))

[62 39 19]
[[62 39 19]]


In [38]:
newLine = np.array([3,4,16])

In [39]:
np.vstack((arr, newLine))

array([[22,  3,  0],
       [ 8,  6,  5],
       [25,  0,  0],
       [ 7,  6, 13],
       [ 0, 24,  1],
       [ 3,  4, 16]])

In [43]:
ones1d = np.ones(5)
print(ones1d, ones1d.shape)

[1. 1. 1. 1. 1.] (5,)


In [47]:
ones2d = ones1d[:,np.newaxis]
print(ones2d,ones2d.shape)
ones2d = ones1d[np.newaxis,:]
print(ones2d,ones2d.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]] (5, 1)
[[1. 1. 1. 1. 1.]] (1, 5)


In [51]:
arr[:,0]

array([22,  8, 25,  7,  0])

In [52]:
arr[0,:]

array([22,  3,  0])

In [54]:
arr[:,0]<arr[:,1]

array([False, False, False, False,  True])

In [56]:
idxes=arr[:,0]>arr[:,1]
arr[idxes,:]

array([[22,  3,  0],
       [ 8,  6,  5],
       [25,  0,  0],
       [ 7,  6, 13]])

In [64]:
#коэффициенты: 2 - да, -1 - нет, -0,5 - воздержались
rate = 2*arr[:,0]-arr[:,1]-0.5*arr[:,2]
rate

array([ 41. ,   7.5,  50. ,   1.5, -24.5])

In [67]:
vect = np.array([2,-1,-0.5])
rate = np.dot(arr,vect)
rate = rate[:,np.newaxis]
rate

array([[ 41. ],
       [  7.5],
       [ 50. ],
       [  1.5],
       [-24.5]])

In [70]:
np.hstack((rate, arr))

array([[ 41. ,  22. ,   3. ,   0. ],
       [  7.5,   8. ,   6. ,   5. ],
       [ 50. ,  25. ,   0. ,   0. ],
       [  1.5,   7. ,   6. ,  13. ],
       [-24.5,   0. ,  24. ,   1. ]])

In [75]:
arr[:,0]

array([22,  8, 25,  7,  0])

In [82]:
np.random.randint(10)

3